repos:
  - repo: local
    hooks:
      - id: swift-build
        name: Swift Build Check
        entry: swift build
        language: system
        pass_filenames: false
        stages: [commit]
        
      - id: static-site-validation
        name: Static Site Validation Tests
        entry: swift test --filter StaticSiteValidationTests
        language: system
        pass_filenames: false
        stages: [commit, push]
